package:
  name: sh
  version: !!str 1.11

source:
  fn: sh-1.11.tar.gz
  url: https://pypi.python.org/packages/source/s/sh/sh-1.11.tar.gz
  md5: 7af8df6c92d29ff927b6db0146bddec3
#  patches:
   # List any patch files here
   # - fix.patch

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - sh

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/amoffat/sh
  license: MIT License
  summary: 'Python subprocess interface'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
