package:
  name: pyublas
  version: 2013.1

source:
  url: https://pypi.python.org/packages/source/P/PyUblas/PyUblas-2013.1.tar.gz#md5=67f686740ea0dae253d7bbb3c5ac17bc
  fn: PyUblas-2013.1.tar.gz
  md5: 67f686740ea0dae253d7bbb3c5ac17bc

build:
  number: 0

requirements:
  build:
    - boost
    - numpy
    - python

  run:
    - boost
    - python
    - numpy

test:
  imports:
    - pyublas

about:
  home: http://mathema.tician.de/software/pyvisfile/
  license: BSD
  summary: Seamless Numpy-UBlas interoperability