package:
  name: openmm
  version: 6.2

source:
  url: https://github.com/pandegroup/openmm/archive/6.2.tar.gz
  fn: 6.2.tar.gz

  patches:
    # remove this after the first release (6.2.1 or 6.3.0) in which
    # PR #780 is part of release
    - openmm-pr-780.patch
build:
  number: 3
  preserve_egg_dir: yes

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake  # [not win]
    - python
    - fftw3f
    - sphinx
    - sphinxcontrib-bibtex
    - swig   # [not win]

  run:
    - python
    - fftw3f # [not win]

test:
  requires:
    - python
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
