package:
  name: pymbar
  version: 3.0.0.beta1

source:
  url: https://github.com/choderalab/pymbar/archive/3.0.0.beta1.tar.gz
  fn: 3.0.0.beta1.tar.gz

build:
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  commands:
    - nosetests
  imports:
    - pymbar
    - pymbar.bar
	
  requires:
    - nose

about:
  home: http://github.com/choderalab/pymbar
  license: LGPL
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR).
