package:
  name: mdtraj
  version: !!str 1.4.0

source:
  fn: 1.4.0.tar.gz
  url: https://github.com/mdtraj/mdtraj/archive/1.4.0.tar.gz
  md5: 97b11eba83429b2ca1b009c6cb1f7c77

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools
    - scripttest

  run:
    - python
    - numpy
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
