package:
  name: mdtraj
  version: !!str 1.4.2

source:
  fn: mdtraj-1.4.2.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.4.2.tar.gz#md5=9ff949cde6623edf47227a734c6f2224
  md5: 9ff949cde6623edf47227a734c6f2224

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools
    - scripttest

  run:
    - python
    - numpy
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
