package:
  name: subprocess32
  version: !!str 3.2.6

source:
  fn: subprocess32-3.2.6.tar.gz
  url: https://pypi.python.org/packages/source/s/subprocess32/subprocess32-3.2.6.tar.gz
  md5: 754c5ab9f533e764f931136974b618f1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - subprocess32

about:
  home: http://code.google.com/p/python-subprocess32/
  license: Python Software Foundation License
  summary: 'Backport of the subprocess module from Python 3.2/3.3 for use on 2.x.'
